# Configuration
minecraft_jar = "C:/Path/to/minecraft.jar"
output = "C:/Path/to/output/dir/"
ignore_cache = false
force_render = true

# Worlds Table
[worlds]
"world_a" = "C:/Path/to/world/dir/"
"world 2" = "C:/Path/to/world/dir/"

# Textures Table
[textures]
"faithful" = "C:/Path/to/resource/packs/Faithful 32x - 1.20.2.zip"

# Renders Table
[[renders]]
world = "world_a"
title = "Normal"
mode = "night"
dimension = "overworld"
textures = "faithful"
crop = { type = "rectangle", x1 = 500, z1 = 500, x2 = -500, y2 = -500}

[[renders]]
world = "world 2"
title = "Nether"
mode = "default"
dimension = "Overworld"
textures = "invalid"
crop = { type = "circle", x = 0, z = 0, radius = 500, diameter = 1000 }

[[renders]]
world = "world_2"
title = "DIM1"
mode = "default"
dimension = "The End"
crop = { type = "square", x = 0, z = 0, size = 500 }

[[renders]]
world = "invalid"
title = "invalid"
mode = "invalid"
dimension = "invalid"
textures = "invalid"